// templates/frontend-react/src/components/admin-layout.tsx
import { Outlet } from "react-router"
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"
import { TooltipProvider } from "@/components/ui/tooltip"
import { AppSidebar } from "@/components/app-sidebar"
import { Header } from "@/components/header"

export function AdminLayout() {
  return (
    <TooltipProvider>
      <SidebarProvider>
        <AppSidebar />
        <SidebarInset>
          <Header />
          <main className="flex-1 overflow-auto px-4 py-6 md:px-6">
            <Outlet />
          </main>
          <footer className="shrink-0 border-t px-4 py-4 text-center text-xs text-muted-foreground">
            © {new Date().getFullYear()} hmilyld. All rights reserved.
          </footer>
        </SidebarInset>
      </SidebarProvider>
    </TooltipProvider>
  )
}

// templates/frontend-vue/src/layouts/AdminLayout.vue
<script setup lang="ts">
import { ref } from 'vue'
import AppSidebar from '@/components/AppSidebar.vue'
import AppHeader from '@/components/AppHeader.vue'
import ToastContainer from '@/components/ToastContainer.vue'

const sidebarCollapsed = ref(false)

function toggleSidebar() {
  sidebarCollapsed.value = !sidebarCollapsed.value
}
</script>

<template>
  <div class="flex h-screen overflow-hidden">
    <AppSidebar
      :collapsed="sidebarCollapsed"
      class="shrink-0 transition-all duration-200"
      :class="sidebarCollapsed ? 'w-16' : 'w-64'"
    />

    <div class="flex flex-1 flex-col overflow-hidden">
      <AppHeader :sidebar-collapsed="sidebarCollapsed" @toggle-sidebar="toggleSidebar" />
      <main class="flex-1 overflow-auto px-4 py-6 md:px-6">
        <router-view />
      </main>
      <footer class="shrink-0 border-t border-base-content/10 px-4 py-3 text-center text-xs text-base-content/40">
        © {{ new Date().getFullYear() }} hmilyld. All rights reserved.
      </footer>
    </div>
    <ToastContainer />
  </div>
</template>
