// frontend-vue/src/components/ThemeToggle.vue
<script setup lang="ts">
import { useThemeStore } from '@/stores/theme'
import { computed } from 'vue'
import { Sun, Moon } from 'lucide-vue-next'

const themeStore = useThemeStore()

const isDark = computed(() => {
  if (themeStore.theme === 'system') {
    return window.matchMedia('(prefers-color-scheme: dark)').matches
  }
  return themeStore.theme === 'dark'
})
</script>

<template>
  <div class="dropdown dropdown-end">
    <div tabindex="0" role="button" class="btn btn-ghost btn-xs btn-square">
      <Transition name="theme-icon" mode="out-in">
        <Sun v-if="!isDark" key="sun" class="size-4" />
        <Moon v-else key="moon" class="size-4" />
      </Transition>
    </div>
    <ul tabindex="0" class="dropdown-content menu bg-base-100 border border-base-content/10 rounded-box z-10 w-32 p-1 shadow-sm">
      <li>
        <button class="text-xs" :class="{ active: themeStore.theme === 'light' }" @click="themeStore.setTheme('light')">浅色</button>
      </li>
      <li>
        <button class="text-xs" :class="{ active: themeStore.theme === 'dark' }" @click="themeStore.setTheme('dark')">深色</button>
      </li>
      <li>
        <button class="text-xs" :class="{ active: themeStore.theme === 'system' }" @click="themeStore.setTheme('system')">跟随系统</button>
      </li>
    </ul>
  </div>
</template>

<style scoped>
.theme-icon-enter-active,
.theme-icon-leave-active {
  transition: all 0.2s ease;
}

.theme-icon-enter-from {
  opacity: 0;
  transform: rotate(-90deg) scale(0.8);
}

.theme-icon-leave-to {
  opacity: 0;
  transform: rotate(90deg) scale(0.8);
}
</style>

// templates/frontend-react/src/components/theme-toggle.tsx
import { MoonIcon, SunIcon } from "lucide-react"
import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { useTheme } from "@/components/theme-provider"

export function ThemeToggle() {
  const { setTheme } = useTheme()

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" size="icon">
          <SunIcon className="rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
          <MoonIcon className="absolute rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
          <span className="sr-only">切换主题</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuGroup>
          <DropdownMenuItem onClick={() => setTheme("light")}>
            浅色
          </DropdownMenuItem>
          <DropdownMenuItem onClick={() => setTheme("dark")}>
            深色
          </DropdownMenuItem>
          <DropdownMenuItem onClick={() => setTheme("system")}>
            跟随系统
          </DropdownMenuItem>
        </DropdownMenuGroup>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
