// templates/frontend-vue/src/pages/settings/AuditLog.vue
<script setup lang="ts">
import { ref, watch, onMounted, computed } from 'vue'
import { getAuditLogs } from '@/lib/api'
import type { AuditLog } from '@/types/api'
import { useToast } from '@/composables/use-toast'
import Pagination from '@/components/shared/Pagination.vue'
import PageSkeleton from '@/components/shared/PageSkeleton.vue'
import { Search, RotateCcw, X } from 'lucide-vue-next'

const toast = useToast()

const PAGE_SIZE = 10

type FilterKey = 'userId' | 'status' | 'action' | 'startTime' | 'endTime'

const FILTER_LABELS: Record<FilterKey, string> = {
  userId: '用户ID',
  status: '状态',
  action: '动作',
  startTime: '开始时间',
  endTime: '结束时间',
}

const logs = ref<AuditLog[]>([])
const tableLoading = ref(true)
const page = ref(1)
const total = ref(0)
const totalPages = ref(1)

// 筛选条件（点击查询后生效）
const userId = ref('')
const status = ref('')
const action = ref('')
const startTime = ref('')
const endTime = ref('')
const query = ref({ userId: '', status: '', action: '', startTime: '', endTime: '' })

async function loadData() {
  tableLoading.value = true
  const res = await getAuditLogs({
    userId: query.value.userId,
    status: query.value.status,
    action: query.value.action,
    startTime: query.value.startTime,
    endTime: query.value.endTime,
    page: page.value,
    pageSize: PAGE_SIZE,
  })
  if (res.code === 0) {
    logs.value = res.data.list
    total.value = res.data.total
    totalPages.value = Math.max(1, Math.ceil(res.data.total / PAGE_SIZE))
  } else {
    toast.error(res.message || '加载数据失败')
  }
  tableLoading.value = false
}

watch(page, () => loadData())

onMounted(loadData)

function handleSearch() {
  page.value = 1
  query.value = {
    userId: userId.value.trim(),
    status: status.value,
    action: action.value.trim(),
    startTime: startTime.value,
    endTime: endTime.value,
  }
}

function handleReset() {
  userId.value = ''
  status.value = ''
  action.value = ''
  startTime.value = ''
  endTime.value = ''
  page.value = 1
  query.value = { userId: '', status: '', action: '', startTime: '', endTime: '' }
}

const activeFilters = computed<{ key: FilterKey; label: string; value: string }[]>(() => {
  const fields: { key: FilterKey; label: string; value: string }[] = [
    { key: 'userId', label: FILTER_LABELS.userId, value: query.value.userId },
    { key: 'status', label: FILTER_LABELS.status, value: query.value.status },
    { key: 'action', label: FILTER_LABELS.action, value: query.value.action },
    { key: 'startTime', label: FILTER_LABELS.startTime, value: query.value.startTime },
    { key: 'endTime', label: FILTER_LABELS.endTime, value: query.value.endTime },
  ]
  return fields.filter((f) => f.value)
})

function removeFilter(key: FilterKey) {
  const clearInput: Record<FilterKey, () => void> = {
    userId: () => (userId.value = ''),
    status: () => (status.value = ''),
    action: () => (action.value = ''),
    startTime: () => (startTime.value = ''),
    endTime: () => (endTime.value = ''),
  }
  clearInput[key]()
  query.value[key] = ''
  if (page.value === 1) {
    loadData()
  } else {
    page.value = 1
  }
}

function clearAllFilters() {
  handleReset()
}

function getStatusBadgeClass(s: string) {
  if (s === 'success') return 'badge badge-primary'
  if (s === 'fail') return 'badge badge-error'
  return 'badge badge-outline'
}

function getStatusLabel(s: string) {
  if (s === 'success') return '成功'
  if (s === 'fail') return '失败'
  return '权限不足'
}

function formatTime(value: string) {
  if (!value) return '-'
  const d = new Date(value)
  if (Number.isNaN(d.getTime())) return value
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`
}
</script>

<template>
  <div class="flex flex-col gap-6">
    <div>
      <h1 class="text-2xl font-bold tracking-tight">审计日志</h1>
      <p class="text-base-content/50">查看系统的写操作与权限拦截记录。</p>
    </div>

    <PageSkeleton v-if="tableLoading" :cols="6" />

    <div v-else class="card border border-base-content/10 rounded-xl">
      <div class="card-body">
        <div class="flex flex-col gap-4">
          <div>
            <h3 class="card-title">操作记录</h3>
            <p class="text-sm text-base-content/50">共 {{ total }} 条记录</p>
          </div>

          <div class="flex flex-wrap items-center gap-2">
            <input v-model="userId" placeholder="用户ID" class="input input-bordered input-sm w-36" />
            <input v-model="status" placeholder="状态" class="input input-bordered input-sm w-32" />
            <input v-model="action" placeholder="动作" class="input input-bordered input-sm w-48" />
            <input v-model="startTime" type="datetime-local" aria-label="开始时间" title="开始时间" class="input input-bordered input-sm w-44" />
            <input v-model="endTime" type="datetime-local" aria-label="结束时间" title="结束时间" class="input input-bordered input-sm w-44" />
            <button class="btn btn-primary btn-sm shrink-0" @click="handleSearch">
              <Search class="size-4" />
              查询
            </button>
            <button class="btn btn-outline btn-sm shrink-0" @click="handleReset">
              <RotateCcw class="size-4" />
              重置
            </button>
          </div>

          <div v-if="activeFilters.length" class="flex flex-wrap items-center gap-2" aria-label="当前筛选条件">
            <span class="text-xs text-base-content/50">当前筛选:</span>
            <button
              v-for="f in activeFilters"
              :key="f.key"
              type="button"
              class="badge badge-outline badge-sm gap-1 rounded-full py-2 pl-3 pr-1.5 transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/40 hover:border-error/40 hover:text-error"
              :title="`移除筛选：${f.label}`"
              @click="removeFilter(f.key)"
            >
              {{ f.label }}: <span class="font-medium">{{ f.value }}</span>
              <X class="size-3 rounded-full bg-base-content/10" />
            </button>
            <button
              type="button"
              class="rounded-sm text-xs text-base-content/50 underline-offset-4 transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/40 hover:text-base-content hover:underline"
              @click="clearAllFilters"
            >
              清除全部
            </button>
          </div>
        </div>

        <div class="overflow-x-auto">
          <table class="table table-zebra">
            <thead>
              <tr>
                <th>时间</th>
                <th>操作者</th>
                <th>动作</th>
                <th>IP</th>
                <th>状态</th>
                <th>详情</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="log in logs" :key="log.id">
                <td class="whitespace-nowrap text-base-content/50">{{ formatTime(log.createdAt) }}</td>
                <td>{{ log.username || '未知' }}</td>
                <td class="font-mono text-xs">{{ log.action }}</td>
                <td class="text-base-content/50">{{ log.ip || '-' }}</td>
                <td>
                  <span :class="getStatusBadgeClass(log.status)">{{ getStatusLabel(log.status) }}</span>
                </td>
                <td class="max-w-[240px] truncate text-base-content/50">{{ log.detail || '-' }}</td>
              </tr>
              <tr v-if="logs.length === 0">
                <td colspan="6" class="text-center text-base-content/50">
                  {{ activeFilters.length ? '没有符合条件的记录，试着放宽筛选条件' : '暂无审计记录，系统的写操作和权限拦截会自动记录在这里' }}
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <Pagination :page="page" :total-pages="totalPages" @update:page="page = $event" />
      </div>
    </div>
  </div>
</template>

// templates/frontend-react/src/pages/settings/audit-log.tsx
import * as React from "react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { TableEmptyRow, TableCardSkeleton } from "@/components/shared/table-states"
import { Pagination } from "@/components/shared/pagination"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Input } from "@/components/ui/input"
import { SearchIcon, RotateCcwIcon, XIcon } from "lucide-react"
import { appToast } from "@/lib/toast"
import type { AuditLog } from "@/types/api"
import { getAuditLogs } from "@/lib/api"

const PAGE_SIZE = 10

type FilterKey = "userId" | "status" | "action" | "startTime" | "endTime"
type AuditFilters = Record<FilterKey, string>

const FILTER_LABELS: Record<FilterKey, string> = {
  userId: "用户ID",
  status: "状态",
  action: "动作",
  startTime: "开始时间",
  endTime: "结束时间",
}

function getStatusBadge(status: AuditLog["status"]) {
  if (status === "success") return <Badge variant="default">成功</Badge>
  if (status === "fail") return <Badge variant="destructive">失败</Badge>
  return <Badge variant="outline">权限不足</Badge>
}

function formatTime(value: string) {
  if (!value) return "-"
  const d = new Date(value)
  if (Number.isNaN(d.getTime())) return value
  return d.toLocaleString("zh-CN", { hour12: false })
}

export function AuditLogPage() {
  const [logs, setLogs] = React.useState<AuditLog[]>([])
  const [tableLoading, setTableLoading] = React.useState(true)

  // 筛选条件（点击查询后生效）
  const [userId, setUserId] = React.useState("")
  const [status, setStatus] = React.useState("")
  const [action, setAction] = React.useState("")
  const [startTime, setStartTime] = React.useState("")
  const [endTime, setEndTime] = React.useState("")
  const [query, setQuery] = React.useState<AuditFilters>({
    userId: "",
    status: "",
    action: "",
    startTime: "",
    endTime: "",
  })

  const [page, setPage] = React.useState(1)
  const [total, setTotal] = React.useState(0)

  const loadData = React.useCallback(async () => {
    setTableLoading(true)
    const res = await getAuditLogs({
      userId: query.userId,
      status: query.status,
      action: query.action,
      startTime: query.startTime,
      endTime: query.endTime,
      page,
      pageSize: PAGE_SIZE,
    })
    if (res.code === 0) {
      setLogs(res.data.list)
      setTotal(res.data.total)
    } else {
      appToast.error(res.message || "加载数据失败")
    }
    setTableLoading(false)
  }, [query, page])

  React.useEffect(() => {
    loadData()
  }, [loadData])

  function handleSearch() {
    setPage(1)
    setQuery({ userId: userId.trim(), status, action: action.trim(), startTime, endTime })
  }

  function handleReset() {
    setUserId("")
    setStatus("")
    setAction("")
    setStartTime("")
    setEndTime("")
    setPage(1)
    setQuery({ userId: "", status: "", action: "", startTime: "", endTime: "" })
  }

  const activeFilters = (Object.keys(query) as FilterKey[])
    .filter((key) => query[key] !== "")
    .map((key) => ({ key, label: FILTER_LABELS[key], value: query[key] }))

  function removeFilter(key: FilterKey) {
    const clearInput: Record<FilterKey, () => void> = {
      userId: () => setUserId(""),
      status: () => setStatus(""),
      action: () => setAction(""),
      startTime: () => setStartTime(""),
      endTime: () => setEndTime(""),
    }
    clearInput[key]()
    setQuery((prev) => ({ ...prev, [key]: "" }))
    setPage(1)
  }

  function clearAllFilters() {
    handleReset()
  }

  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE))
  const safePage = Math.min(page, totalPages)

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">审计日志</h1>
        <p className="text-muted-foreground">查看系统的写操作与权限拦截记录。</p>
      </div>

      {tableLoading ? (
        <TableCardSkeleton colSpan={6} />
      ) : (
        <Card>
          <CardHeader>
            <div className="flex flex-col gap-4">
              <div>
                <CardTitle>操作记录</CardTitle>
                <CardDescription>共 {total} 条记录</CardDescription>
              </div>
              <div className="flex flex-wrap items-center gap-2">
                <Input
                  placeholder="用户ID"
                  value={userId}
                  onChange={(e) => setUserId(e.target.value)}
                  className="w-36"
                />
                <Input
                  placeholder="状态"
                  value={status}
                  onChange={(e) => setStatus(e.target.value)}
                  className="w-32"
                />
                <Input
                  placeholder="动作"
                  value={action}
                  onChange={(e) => setAction(e.target.value)}
                  className="w-48"
                />
                <Input
                  type="datetime-local"
                  aria-label="开始时间"
                  title="开始时间"
                  value={startTime}
                  onChange={(e) => setStartTime(e.target.value)}
                  className="w-44"
                />
                <Input
                  type="datetime-local"
                  aria-label="结束时间"
                  title="结束时间"
                  value={endTime}
                  onChange={(e) => setEndTime(e.target.value)}
                  className="w-44"
                />
                <Button onClick={handleSearch} className="shrink-0">
                  <SearchIcon data-icon="inline-start" />
                  查询
                </Button>
                <Button variant="outline" onClick={handleReset} className="shrink-0">
                  <RotateCcwIcon data-icon="inline-start" />
                  重置
                </Button>
              </div>
              {activeFilters.length > 0 && (
                <div className="flex flex-wrap items-center gap-2" aria-label="当前筛选条件">
                  <span className="text-xs text-muted-foreground">当前筛选:</span>
                  {activeFilters.map((f) => (
                    <button
                      key={f.key}
                      type="button"
                      onClick={() => removeFilter(f.key)}
                      title={`移除筛选：${f.label}`}
                      className="inline-flex items-center gap-1.5 rounded-full border bg-background py-1 pl-3 pr-1.5 text-xs transition-colors outline-none select-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/30 hover:border-destructive/40 hover:text-destructive"
                    >
                      <span>
                        {f.label}: <span className="font-medium">{f.value}</span>
                      </span>
                      <XIcon className="size-3.5 rounded-full bg-muted p-0.5" />
                    </button>
                  ))}
                  <button
                    type="button"
                    onClick={clearAllFilters}
                    className="rounded-sm text-xs text-muted-foreground underline-offset-4 transition-colors outline-none select-none hover:text-foreground hover:underline focus-visible:ring-3 focus-visible:ring-ring/30"
                  >
                    清除全部
                  </button>
                </div>
              )}
            </div>
          </CardHeader>
          <CardContent>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>时间</TableHead>
                  <TableHead>操作者</TableHead>
                  <TableHead>动作</TableHead>
                  <TableHead>IP</TableHead>
                  <TableHead>状态</TableHead>
                  <TableHead>详情</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {logs.map((log) => (
                  <TableRow key={log.id}>
                    <TableCell className="whitespace-nowrap text-muted-foreground">
                      {formatTime(log.createdAt)}
                    </TableCell>
                    <TableCell>{log.username || "未知"}</TableCell>
                    <TableCell className="font-mono text-xs">{log.action}</TableCell>
                    <TableCell className="text-muted-foreground">{log.ip || "-"}</TableCell>
                    <TableCell>{getStatusBadge(log.status)}</TableCell>
                    <TableCell className="max-w-[240px] truncate text-muted-foreground">
                      {log.detail || "-"}
                    </TableCell>
                  </TableRow>
                ))}
                {!tableLoading && logs.length === 0 && (
                  <TableEmptyRow
                    colSpan={6}
                    text={
                      activeFilters.length > 0
                        ? "没有符合条件的记录，试着放宽筛选条件"
                        : "暂无审计记录，系统的写操作和权限拦截会自动记录在这里"
                    }
                  />
                )}
              </TableBody>
            </Table>

            <Pagination page={safePage} totalPages={totalPages} onPageChange={setPage} />
          </CardContent>
        </Card>
      )}
    </div>
  )
}
