// templates/frontend-vue/src/pages/dashboard/Index.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { getDashboardStats, getDashboardActivity } from '@/api/dashboard'
import type { DashboardStats, ActivityItem } from '@/types/dashboard'
import {
  Users,
  Activity,
  DollarSign,
  TrendingUp,
} from 'lucide-vue-next'

const stats = ref<DashboardStats | null>(null)
const activity = ref<ActivityItem[]>([])
const loading = ref(true)

onMounted(async () => {
  const [statsRes, activityRes] = await Promise.all([
    getDashboardStats(),
    getDashboardActivity(),
  ])
  if (statsRes.code === 0) stats.value = statsRes.data
  if (activityRes.code === 0) activity.value = activityRes.data
  loading.value = false
})

const statItems = [
  { title: '总用户数', key: 'totalUsers' as const, icon: Users, change: '+20.1%', description: '较上月' },
  { title: '当前活跃', key: 'activeNow' as const, icon: Activity, change: '+12.2%', description: '较上小时' },
  { title: '收入', key: 'revenue' as const, icon: DollarSign, change: '+15.3%', description: '较上月' },
  { title: '增长率', key: 'growth' as const, icon: TrendingUp, change: '+4.5%', description: '较上季度' },
]
</script>

<template>
  <div class="flex flex-col gap-6">
    <div>
      <h1 class="text-xl font-semibold">仪表盘</h1>
      <p class="text-sm text-base-content/50">欢迎回来，以下是您的项目概览。</p>
    </div>

    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <template v-if="loading">
        <div v-for="i in 4" :key="i" class="card border border-base-content/10 rounded-xl bg-transparent">
          <div class="card-body">
            <div class="skeleton h-3 w-16"></div>
            <div class="skeleton mb-1 h-6 w-20"></div>
            <div class="skeleton h-3 w-24"></div>
          </div>
        </div>
      </template>
      <template v-else>
        <div v-for="stat in statItems" :key="stat.title" class="card border border-base-content/10 rounded-xl bg-transparent">
          <div class="card-body">
            <div class="flex items-center justify-between">
              <span class="text-xs text-base-content/50">{{ stat.title }}</span>
              <component :is="stat.icon" class="size-4 text-base-content/30" />
            </div>
            <div class="text-xl font-semibold">{{ stats?.[stat.key] }}</div>
            <p class="text-xs text-base-content/40">
              <span class="text-success">{{ stat.change }}</span>
              {{ stat.description }}
            </p>
          </div>
        </div>
      </template>
    </div>

    <div class="grid gap-4 md:grid-cols-2">
      <div class="card border border-base-content/10 rounded-xl bg-transparent">
        <div class="card-body">
          <h3 class="text-sm font-medium">最近动态</h3>
          <div class="flex flex-col gap-3">
            <template v-if="loading">
              <div v-for="i in 5" :key="i" class="flex items-center justify-between">
                <div class="flex flex-col gap-1">
                  <div class="skeleton h-3 w-16"></div>
                  <div class="skeleton h-3 w-28"></div>
                </div>
                <div class="skeleton h-3 w-12"></div>
              </div>
            </template>
            <template v-else>
              <div v-for="item in activity" :key="item.user" class="flex items-center justify-between">
                <div class="flex flex-col">
                  <span class="text-sm">{{ item.user }}</span>
                  <span class="text-xs text-base-content/40">{{ item.action }}</span>
                </div>
                <span class="text-xs text-base-content/40">{{ item.time }}</span>
              </div>
            </template>
          </div>
        </div>
      </div>

      <div class="card border border-base-content/10 rounded-xl bg-transparent">
        <div class="card-body">
          <h3 class="text-sm font-medium">快捷操作</h3>
          <div class="flex flex-col gap-2">
            <div
              v-for="action in [
                { label: '创建项目', desc: '开始一个新的工作空间' },
                { label: '邀请团队', desc: '添加协作者' },
                { label: '查看报表', desc: '数据分析与洞察' },
                { label: '管理账单', desc: '更新支付方式' },
              ]"
              :key="action.label"
              class="flex cursor-pointer items-center justify-between rounded-xl border border-base-content/10 p-3 transition-colors hover:border-base-content/20"
            >
              <div>
                <div class="text-sm">{{ action.label }}</div>
                <div class="text-xs text-base-content/40">{{ action.desc }}</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// templates/frontend-react/src/pages/dashboard/index.tsx
import * as React from "react"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Skeleton } from "@/components/ui/skeleton"
import { UsersIcon, ActivityIcon, DollarSignIcon, TrendingUpIcon } from "lucide-react"
import { getDashboardStats, getDashboardActivity } from "@/api/dashboard"
import type { DashboardStats, ActivityItem } from "@/types/dashboard"

export function DashboardPage() {
  const [stats, setStats] = React.useState<DashboardStats | null>(null)
  const [activity, setActivity] = React.useState<ActivityItem[]>([])
  const [loading, setLoading] = React.useState(true)

  React.useEffect(() => {
    async function load() {
      const [statsRes, activityRes] = await Promise.all([
        getDashboardStats(),
        getDashboardActivity(),
      ])
      if (statsRes.code === 0) setStats(statsRes.data)
      if (activityRes.code === 0) setActivity(activityRes.data)
      setLoading(false)
    }
    load()
  }, [])

  const statItems = stats
    ? [
        { title: "总用户数", value: String(stats.totalUsers), change: "+20.1%", icon: UsersIcon, description: "较上月" },
        { title: "当前活跃", value: String(stats.activeNow), change: "+12.2%", icon: ActivityIcon, description: "较上小时" },
        { title: "收入", value: stats.revenue, change: "+15.3%", icon: DollarSignIcon, description: "较上月" },
        { title: "增长率", value: stats.growth, change: "+4.5%", icon: TrendingUpIcon, description: "较上季度" },
      ]
    : []

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">仪表盘</h1>
        <p className="text-muted-foreground">
          欢迎回来，以下是您的项目概览。
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {loading
          ? Array.from({ length: 4 }).map((_, i) => (
              <Card key={i}>
                <CardHeader className="flex flex-row items-center justify-between pb-2">
                  <Skeleton className="h-4 w-20" />
                  <Skeleton className="size-4" />
                </CardHeader>
                <CardContent>
                  <Skeleton className="mb-2 h-8 w-24" />
                  <Skeleton className="h-3 w-32" />
                </CardContent>
              </Card>
            ))
          : statItems.map((stat) => (
              <Card key={stat.title}>
                <CardHeader className="flex flex-row items-center justify-between pb-2">
                  <CardTitle className="text-sm font-medium">{stat.title}</CardTitle>
                  <stat.icon className="text-muted-foreground" />
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{stat.value}</div>
                  <p className="text-xs text-muted-foreground">
                    <Badge variant="secondary" className="mr-1">
                      {stat.change}
                    </Badge>
                    {stat.description}
                  </p>
                </CardContent>
              </Card>
            ))}
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>最近动态</CardTitle>
            <CardDescription>工作区中的最新操作记录。</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex flex-col gap-4">
              {loading
                ? Array.from({ length: 5 }).map((_, i) => (
                    <div key={i} className="flex items-center justify-between">
                      <div className="flex flex-col gap-1">
                        <Skeleton className="h-4 w-16" />
                        <Skeleton className="h-3 w-32" />
                      </div>
                      <Skeleton className="h-3 w-16" />
                    </div>
                  ))
                : activity.map((item) => (
                    <div key={item.user} className="flex items-center justify-between">
                      <div className="flex flex-col">
                        <span className="text-sm font-medium">{item.user}</span>
                        <span className="text-xs text-muted-foreground">{item.action}</span>
                      </div>
                      <span className="text-xs text-muted-foreground">{item.time}</span>
                    </div>
                  ))}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>快捷操作</CardTitle>
            <CardDescription>常用的操作入口。</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid gap-2">
              {[
                { label: "创建项目", desc: "开始一个新的工作空间" },
                { label: "邀请团队", desc: "添加协作者" },
                { label: "查看报表", desc: "数据分析与洞察" },
                { label: "管理账单", desc: "更新支付方式" },
              ].map((action) => (
                <div
                  key={action.label}
                  className="flex cursor-pointer items-center justify-between rounded-md border p-3 transition-colors hover:bg-muted"
                >
                  <div>
                    <div className="text-sm font-medium">{action.label}</div>
                    <div className="text-xs text-muted-foreground">{action.desc}</div>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
